### ISSUE TITLE
Crash as notification should have arrived

### ISSUE THREAD

**Issue by MilkyW** [Agasper/unity-android-notifications#105]
I am trying the latest commit and the NotificationTest demo scene.
After I hit the buttion and 5 seconds later, no notification in bar, no sound and no vibration, but the app crashed (when the notification should have arrived).
**adb log:**
--------- beginning of crash
07-23 12:33:09.839 11398 11398 E AndroidRuntime: FATAL EXCEPTION: main
07-23 12:33:09.839 11398 11398 E AndroidRuntime: Process: net.agasper.notificationtest, PID: 11398
07-23 12:33:09.839 11398 11398 E AndroidRuntime: java.lang.Error: FATAL EXCEPTION [main]
07-23 12:33:09.839 11398 11398 E AndroidRuntime: Unity version     : 2018.1.6f1
07-23 12:33:09.839 11398 11398 E AndroidRuntime: Device model      : OPPO OPPO R11
07-23 12:33:09.839 11398 11398 E AndroidRuntime: Device fingerprint: OPPO/R11/R11:7.1.1/NMF26X/1521488902:user/release-keys
07-23 12:33:09.839 11398 11398 E AndroidRuntime: 
07-23 12:33:09.839 11398 11398 E AndroidRuntime: Caused by: java.lang.RuntimeException: Unable to start receiver net.agasper.unitynotification.UnityNotificationManager: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList android.os.Bundle.getParcelableArrayList(java.lang.String)' on a null object reference
07-23 12:33:09.839 11398 11398 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3284)
07-23 12:33:09.839 11398 11398 E AndroidRuntime: 	at android.app.ActivityThread.-wrap18(ActivityThread.java)
07-23 12:33:09.839 11398 11398 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1732)
07-23 12:33:09.839 11398 11398 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-23 12:33:09.839 11398 11398 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:185)
07-23 12:33:09.839 11398 11398 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6615)
07-23 12:33:09.839 11398 11398 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-23 12:33:09.839 11398 11398 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:916)
07-23 12:33:09.839 11398 11398 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:806)
07-23 12:33:09.839 11398 11398 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList android.os.Bundle.getParcelableArrayList(java.lang.String)' on a null object reference
07-23 12:33:09.839 11398 11398 E AndroidRuntime: 	at net.agasper.unitynotification.UnityNotificationManager.onReceive(UnityNotificationManager.java:153)
07-23 12:33:09.839 11398 11398 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3270)
07-23 12:33:09.839 11398 11398 E AndroidRuntime: 	... 8 more

**Comment by zulqarnain26** [comment]
Any solution yet ?
