### ISSUE TITLE
OnAction not working

### ISSUE THREAD

**Issue by MvanDoorn** [Agasper/unity-android-notifications#80]
When testing on Android, the OnAction callback is never called when selecting the notification. It doesn't work in my own implementation and also not in the NotificationTest example.

All the notifications are working fine but when i tap on a notification, it opens the app but OnAction is never called.

Only tested on Android 7.0 with a Samsung Galaxy S7 (SM-G930F).

**Comment by irina88** [comment]
I am having the same issue. The game crashes:

FATAL EXCEPTION: main
Process: com.Company.AppName, PID: 24804
java.lang.Error: FATAL EXCEPTION[main]
Unity version     : 2017.3.1f1
Device model      : samsung SM-G935F
Device fingerprint: samsung / hero2ltexx / hero2lte:7.0 / NRD90M / G935FXXS2DRA9:user / release - keys

Caused by: java.lang.RuntimeException: Unable to start receiver net.agasper.unitynotification.UnityNo
  tificationManager: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a n
  ull object reference
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3313)
        at android.app.ActivityThread.-wrap20(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1719)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android
.content.Context.getPackageName()' on a null object reference
        at android.content.ComponentName.<init>(ComponentName.java:128)
        at android.content.Intent.<init>(Intent.java:5359)
        at net.agasper.unitynotification.UnityNotificationManager.buildActionIntent(UnityNotificationM
anager.java:208)
        at net.agasper.unitynotification.UnityNotificationManager.onReceive(UnityNotificationManager.java:198)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3306)
        ... 8 more
 KPU : put[com.android.settings] : 8300 K
 Killing 24065:com.android.settings/1000 (adj 906): DHA:empty #33
