### ISSUE TITLE
App Crush on notification send

### ISSUE THREAD

**Issue by rmahdi11** [Agasper/unity-android-notifications#94]
hello,
app crush on notification begin to send , i am using the latest version of "notification.jar";
`Caused by: java.lang.RuntimeException: Unable to start receiver net.agasper.unitynotification.UnityNotificationManager: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList android.os.Bundle.getParcelableArrayList(java.lang.String)' on a null object reference
                                                     at android.app.ActivityThread.handleReceiver(ActivityThread.java:3060)
                                                     at android.app.ActivityThread.access$1800(ActivityThread.java:190)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
                                                     at android.os.Handler.dispatchMessage(Handler.java:111)
                                                     at android.os.Looper.loop(Looper.java:207)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5927)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:958)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:819)
                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList android.os.Bundle.getParcelableArrayList(java.lang.String)' on a null object reference
                                                     at net.agasper.unitynotification.UnityNotificationManager.onReceive(UnityNotificationManager.java:153)
                                                     at android.app.ActivityThread.handleReceiver(ActivityThread.java:3045)
                                                     at android.app.ActivityThread.access$1800(ActivityThread.java:190) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                     at android.os.Looper.loop(Looper.java:207) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5927) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:958) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:819) `

**Comment by Agasper** [comment]
Please check your method parameters or use the example

**Comment by MilkyW** [comment]
I am trying the example but having the same problem.
